FN.Store/FN.Store.UI.Web/Controllers/ClientesController.cs
using FN.Store.Data.EF;
using FN.Store.Data.EF.Repository;
using FN.Store.Domain.Entities;
using FN.Store.Domain.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FN.Store.UI.Web.Controllers
{
    public class ClientesController : Controller
    {
        //
        // GET: /Clientes/

        //private readonly StoreDataContext contexto = new StoreDataContext();
        private readonly IClienteRepository _clienteRepo =
            new ClienteRepository();

        public ActionResult Index()
        {
            //var clientes = contexto.Clientes.ToList();
            var clientes = _clienteRepo.Obter();
            return View(clientes);
        }

        public ActionResult Novo()
        {
            return View("AddEdit", new Cliente());
        }

        public ActionResult Editar(int id)
        {
            //var cliente = contexto.Clientes.Find(id);
            var cliente = _clienteRepo.Obter(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }

            return View("AddEdit", cliente);
        }

        public ActionResult Salvar(Cliente cli)
        {
            if (ModelState.IsValid)
            {
                if (cli.Id == 0)
                {
                    //contexto.Clientes.Add(cli);
                    _clienteRepo.Adicionar(cli);
                }
                else
                {
                    //contexto.Entry(cli).State = System.Data.Entity.EntityState.Modified;
                    _clienteRepo.Editar(cli);
                }


                //contexto.SaveChanges();
            }
            else
            {
                return View("Novo");
            }

            return RedirectToAction("Index");
        }


        public JsonResult Excluir(int id)
        {
            var sucesso = true;
            var mensagem = "excluído c/ sucesso";

            //var cli = contexto.Clientes.Find(id);
            var cli = _clienteRepo.Obter(id);

            if (cli == null)
            {
                sucesso = false;
                mensagem = "cliente não existe";
            }
            else
            {
                //contexto.Clientes.Remove(cli);
                //contexto.SaveChanges();
                _clienteRepo.Excluir(cli);
            }

            return Json(new { sucesso = sucesso, mensagem = mensagem });
        }


        protected override void Dispose(bool disposing)
        {
            //contexto.Dispose();
            _clienteRepo.Dispose();
        }

    }
}

FN.Store/FN.Store.UI.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FN.Store.UI.Web.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

FN.Store/FN.Store.UI.Web/Views/Clientes/AddEdit.cshtml
@model FN.Store.Domain.Entities.Cliente

@{
    ViewBag.Title = "Novo";
}

<h2>Novo Cliente</h2>

<div class="row">
    <div class="col-sm-6">

        @using (Html.BeginForm("Salvar", "Clientes", FormMethod.Post))
        { 
            @Html.HiddenFor(x=>x.Id)

            <div class="form-group">
                <label>Nome</label>
                @Html.TextBoxFor(x => x.Nome, new { @class = "form-control", autofocus = "" })
            </div>
    
            <div class="form-group">
                <label>Nascimento</label>
                @Html.TextBoxFor(x => x.DataNascimento, new { @class = "form-control"})
            </div>
    
            <div class="form-group">
                <label>Sexo</label>
                <select class="form-control" name="sexo">
                    @if (Model.Sexo == 0)
                    {
                        <option value="0" selected>Feminino</option>
                        <option value="1">Masculino</option>
                    }
                    else
                    {
                        <option value="0">Feminino</option>
                        <option value="1" selected>Masculino</option>
                    }
                </select>
            </div>
    
            <button class="btn btn-default">Salvar</button>
            <a class="btn btn-danger" href="@Url.Action("Index")">Cancelar</a>
        }
    </div>
</div>

FN.Store/FN.Store.UI.Web/Views/Clientes/Index.cshtml
@model IEnumerable<FN.Store.Domain.Entities.Cliente>

@{
    ViewBag.Title = "Index";
}

<h2>Clientes</h2>

<div>
    <a class="btn btn-success" href="@Url.Action("Novo")">Adicionar</a>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nome</th>
            <th>Nascimento</th>
            <th>Tels</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var cli in Model)
        {
            <tr>
                <td>@cli.Id</td>
                <td>@cli.Nome</td>
                <td>@cli.DataNascimento</td>
                <td>@string.Join(" | ",cli.Telefones.Select(x=>x.Numero))</td>
                <td>
                    <a href="@Url.Action("Editar", new { id=cli.Id })" class="btn btn-info"><i class="glyphicon glyphicon-pencil"></i> Editar</a>
                    <button onclick="excluir(@cli.Id)" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i> Excluir</button>
                </td>
            </tr> 
        }
    </tbody>
</table>
<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Exclusão</h4>
      </div>
      <div class="modal-body">
          <p>Quer excluir o cliente <span id="cli-id"></span>?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <button id="confirmar-del" type="button" class="btn btn-primary">Confirmar</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


@section scripts{
    
    <script>

        var url = "@Url.Action("Excluir")";

        $("#confirmar-del").click(function () {
            var id = $("#cli-id").text();

            $.ajax({
                url: url,
                type: "post",
                data: { id: id },
                success: function (resp) {
                    //console.log(resp);
                    if (resp.sucesso) {
                        $("#modal-delete").modal("hide");
                        window.location.reload();
                    } else {
                        alert(resp.mensagem);
                    }

                }
            });
            //alert("excluir " + $("#cli-id").text());
        });

        function excluir(id) {
            $("#cli-id").text(id);
            $("#modal-delete").modal("show");
        }

        
    </script>
    
    }

FN.Store/FN.Store.UI.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Bem vindo ao FNStore</h2>

FN.Store/FN.Store.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    @Html.Partial("_menu")


    <div class="container">
        @RenderBody()
    </div>

    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    

    @RenderSection("scripts", required: false)
</body>
</html>

FN.Store/FN.Store.UI.Web/Views/Shared/_menu.cshtml
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Index","Home")">FN Store</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="@Url.Action("Index","Clientes")">Clientes</a></li>
                <li><a href="#">Produtos</a></li>
            </ul>
            
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>